name: SSH Test

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
